spring.application.name=emailsender

spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=contato@humanconsulting.com.br
spring.mail.password=13042018Rw#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

# spring.rabbitmq.host=10.0.0.82
# spring.rabbitmq.port=5672
# spring.rabbitmq.username=myuser
# spring.rabbitmq.password=MyRabbitPass
# spring.rabbitmq.virtual-host=myvhost

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

server.port=8081